name: base_arithmetic
description: Dart library for base arithmetic
version: 1.0.0
repository: https://github.com/Clique-Paris/dart-base-arithmetic
homepage: https://github.com/Clique-Paris/dart-base-arithmetic
documentation: https://github.com/Clique-Paris/dart-base-arithmetic/blob/master/README.md

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
